#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
for i in "$DIR"/*.c
do
  echo "$i"
  clang -O0 -emit-llvm "$i" -c -o "${i%.*}".bc
done

for i in "$DIR"/*.bc
do
  echo "$i"
  opt -load "$DIR"/../GlobalApproxCheck/libGlobalApproxCheck.so -GlobalApproxCheck -disable-output "$i"
done
